// src/js/readingList/react/src/components/Pagination.tsx
import { useAppSelector, useAppDispatch } from '../hooks';

import type { BookResults } from '../../../shared/types/results';
import { createTaxonomyArray } from '../../../shared/utils/createTaxonomyArray.js';
import { useFetch } from '../../../shared/utils/useFetch.js';
import { config } from '../../../shared/config/config.js';
import { booksQuery } from '../../../shared/graphql/books.js';

import { setLoading, appendResults } from '../store/slices/resultsSlice.js';

export function Pagination() {

	const dispatch = useAppDispatch();

	const filters = useAppSelector((state) => state.filters);
	const pageInfo = useAppSelector((state) => state.results.pageInfo);

	function loadMore() {

		const taxArray = createTaxonomyArray(
			filters.bookFormats,
			filters.bookTypes,
			filters.bookYears,
		);

		function dispatchToAppendResults(results: BookResults) {
			dispatch(appendResults(results));
		}

		useFetch({
			url: config.url,
			query: booksQuery({
				'taxArray': taxArray,
				'first': config.resultsPerPage.toString(),
				'after': pageInfo.endCursor,
			}),
			callback: dispatchToAppendResults,
			useCache: false,
		});

	}

	return (
		<button
			onClick={loadMore}
			className="button center"
		>
			Load more
		</button>
	)
}

// src/js/readingList/vue/src/components/Pagination.vue
<template src='./templates/Pagination.html' />

<script setup lang="ts">

import { config } from '../../../shared/config/config';

import { booksQuery } from '../../../shared/graphql/books';

import { createTaxonomyArray } from '../../../shared/utils/createTaxonomyArray';
import { useFetch } from '../../../shared/utils/useFetch';

import { useFiltersStore } from '../stores/filtersStore';
import { useResultsStore } from '../stores/resultsStore';

const filtersStore = useFiltersStore();
const resultsStore = useResultsStore();

function loadMore() {

    const taxArray = createTaxonomyArray(
        filtersStore.bookFormats,
        filtersStore.bookTypes,
        filtersStore.bookYears,
    );

    useFetch({
        url: config.url,
        query: booksQuery({
            taxArray: taxArray,
            first: config.resultsPerPage.toString(),
            after: resultsStore.pageInfo.endCursor,
        }),
        callback: resultsStore.appendResults,
        useCache: false,
    });

}

</script>
