// src/js/readingList/react/src/components/Pagination.jsx
import { useSelector, useDispatch } from 'react-redux';

import { createTaxonomyArray } from '../../../shared/utils/createTaxonomyArray.js';
import { useFetch } from '../../../shared/utils/useFetch.js';
import { config } from '../../../shared/config/config.js';
import { booksQuery } from '../../../shared/graphql/books.js';

import { setLoading, appendResults } from '../store/slices/resultsSlice.js';

export function Pagination() {

	const dispatch = useDispatch();

	const filters = useSelector((state) => state.filters);
    const pageInfo = useSelector((state) => state.results.pageInfo);

	function loadMore(){

		const taxArray = createTaxonomyArray(filters);

        function dispatchToAppendResults(results) {
            dispatch(appendResults(results));
        }
	    
	    useFetch({
	        url: config.url,
	        query: booksQuery({
	            'taxArray': taxArray,
	            'first': config.resultsPerPage,
	            'after': pageInfo.endCursor,
	        }),
	        callback: dispatchToAppendResults,
	        useCache: false,
	    });

	}

	return (
		<button
		    onClick={loadMore}
		    className="button center"
		>
		    Load more
		</button>
	)
}

// src/js/readingList/vue/src/components/Pagination.vue
<template src='./templates/Pagination.html' />

<script setup>

	import { config } from '../../../shared/config/config.js';

    import { booksQuery } from '../../../shared/graphql/books.js';

	import { createTaxonomyArray } from '../../../shared/utils/createTaxonomyArray.js';
	import { useFetch } from '../../../shared/utils/useFetch.js';

	import { useFiltersStore } from '../stores/filtersStore.js';
	import { useResultsStore } from '../stores/resultsStore.js';
	
	const filtersStore = useFiltersStore();
	const resultsStore = useResultsStore();

	function loadMore(){

		const taxArray = createTaxonomyArray(filtersStore);
    
        useFetch({
            url: config.url,
            query: booksQuery({
                'taxArray': taxArray,
                'first': config.resultsPerPage,
                'after': resultsStore.pageInfo.endCursor,
            }),
            callback: resultsStore.appendResults,
            useCache: false,
        });

	}

</script>
