// src/js/readingList/vue/src/components/Filters.vue
<template src='./templates/Filters.html' />

<script setup lang="ts">

import Filter from './Filter.vue';

import { watch } from 'vue';

import { config } from '../../../shared/config/config.ts';

import { createTaxonomyArray } from '../../../shared/utils/createTaxonomyArray.ts';
import { useFetch } from '../../../shared/utils/useFetch.ts';

import { booksQuery } from '../../../shared/graphql/books.ts';

import { useFiltersStore } from '../stores/filtersStore.ts';
import { useResultsStore } from '../stores/resultsStore.ts';

const filtersStore = useFiltersStore();
const resultsStore = useResultsStore();

/*
    grab new results whenever our filters change!
*/
watch(filtersStore, () => {

    resultsStore.setLoading(true);

    const taxArray = createTaxonomyArray(
        filtersStore.bookFormats,
        filtersStore.bookTypes,
        filtersStore.bookYears,
    );

    useFetch({
        url: config.url,
        query: booksQuery({
            'taxArray': taxArray,
            'first': config.resultsPerPage.toString(),
            'after': '0',
        }),
        callback: resultsStore.updateResults,
    });

});


</script>

// src/js/readingListReact/src/components/Filters.jsx
import { useEffect } from 'react';
import { useSelector, useDispatch } from 'react-redux';
import { updateResults } from '../store/slices/resultsSlice.js';

import { config } from '../config/config.js';
import { booksQuery } from '../graphql/books.js';
import { createTaxonomyArray } from '../utils/createTaxonomyArray.js';
import { useFetch } from '../utils/useFetch.js';

import { Filter } from './Filter';

export function Filters() {

    const dispatch = useDispatch();

    const filters = useSelector((state) => state.filters);

    // every time the filters change...
    useEffect(() => {

        const taxArray = createTaxonomyArray(filters);
        
        // ...grab the results
        function dispatchToUpdateResults(results) {
            dispatch(updateResults(results));
        }

        useFetch({
            url: config.url,
            query: booksQuery({
                'taxArray': taxArray,
                'first': config.resultsPerPage,
                'after': 0,
            }),
            callback: dispatchToUpdateResults,
        });

    }, [filters]);

    return (
        <div>
            <h2 className="h5 top-margin">
                Filter by:
            </h2>

            <Filter id="bookFormats" name="Format" filter={filters.bookFormats}/>
            <Filter id="bookTypes" name="Genre" filter={filters.bookTypes}/>
            <Filter id="bookYears" name="Year" filter={filters.bookYears}/>
        </div>
    )
};
