// src/js/readingList/react/src/App.tsx
import { useEffect } from 'react';
import { useSelector, useDispatch } from 'react-redux';

import { config } from '../../shared/config/config.js';
import { useFetch } from '../../shared/utils/useFetch.js';
import { filtersQuery } from '../../shared/graphql/filters.js';

import { updateFilters } from './store/slices/filtersSlice.js';
import { updateResults } from './store/slices/resultsSlice.js';

import { Loading } from './components/Loading';
import { Filters } from './components/Filters';
import { IntroText } from './components/IntroText';
import { Results } from './components/Results';
import { Pagination } from './components/Pagination';

function App() {

    const dispatch = useDispatch();

    const pageInfo = useSelector((state) => state.results.pageInfo);

    // when the app first mounts...
    useEffect(() => {

        // ...setup our filters
        function dispatchToUpdateFilters(filters) {
            dispatch(updateFilters(filters));
        }

        useFetch({
            url: config.url,
            query: filtersQuery(),
            callback: dispatchToUpdateFilters,
        });

    }, []);
    
    const areFiltersLoading = useSelector((state) => state.filters.loading);
    const areResultsLoading = useSelector((state) => state.results.loading);

    return (
        <section>
            { 
                areFiltersLoading 
                ? 
                    <Loading /> 
                : 
                    <div>
                        <Filters />
                        { 
                            areResultsLoading
                            ?
                                <Loading />
                            :
                                <div>
                                    <IntroText />
                                    <Results />
                                    {   
                                        pageInfo.hasNextPage &&
                                            <Pagination />
                                    }
                                </div>
                        }
                    </div>
            }
        </section>
    )
}

export default App;

// src/js/readingList/vue/src/App.vue
<template src='./components/templates/App.html' />

<script setup>

    import { config } from '../../shared/config/config.js';

    import { booksQuery } from '../../shared/graphql/books.js';
    import { filtersQuery } from '../../shared/graphql/filters.js';

    import { useFetch } from './../../shared/utils/useFetch.js';

    import Filters from './components/Filters.vue';
    import Results from './components/Results.vue';
    import Pagination from './components/Pagination.vue';

    import { useResultsStore } from './stores/resultsStore.js';
    import { useFiltersStore } from './stores/filtersStore.js';

    const resultsStore = useResultsStore();
    const filtersStore = useFiltersStore();

    // 1: setup filters
    useFetch({
        url: config.url,
        query: filtersQuery(),
        callback: filtersStore.updateFilters,
    });

    // 2: grab initial results
    useFetch({
        url: config.url,
        query: booksQuery({
            'taxArray': `[]`,
            'first': config.resultsPerPage,
            'after': 0,
        }),
        callback: resultsStore.updateResults,
    });

</script>
